# Generated by Django 5.1.3 on 2024-11-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=400)),
                ('commentNum', models.IntegerField()),
                ('repostNum', models.IntegerField()),
                ('likesNum', models.IntegerField()),
            ],
        ),
    ]
